# Generated by Django 2.1.15 on 2020-11-18 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201118_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='creation',
        ),
    ]
